language: go

go:
  - 1.9.2

sudo: true

before_install:
  - go get github.com/bradfitz/gomemcache/memcache
  - go get github.com/garyburd/redigo/internal
  - go get github.com/garyburd/redigo/redis
  - go get github.com/go-sql-driver/mysql
  - go get github.com/golang/freetype

script:
  - curl https://glide.sh/get | sh
  - glide update
  - GO_ENABLED=1 go build -v -x -tags "pam" && go install

before_deploy:
  - sudo apt-get -qq update
  - CGO_ENABLED=1 GOARCH=amd64 GOOS=linux go build -o mindoc_linux_amd64 -ldflags="-w -X github.com/lifei6671/mindoc/conf.VERSION=$TRAVIS_TAG -X 'github.com/lifei6671/mindoc/conf.BUILD_TIME=`date`' -X 'conf.GO_VERSION=`github.com/lifei6671/mindoc/go version`'"
  - rm -rf commands controllers models modules data routers tasks vendor docs search utils graphics .git Godeps uploads/* .gitignore .travis.yml Dockerfile gide.yaml LICENSE main.go README.md conf/enumerate.go conf/mail.go install.lock *.md
  - cp conf/app.conf.example conf/app.conf
  - zip -r mindoc_linux_amd64.zip conf logs static uploads views lib mindoc_linux_amd64



deploy:
  provider: releases
  api_key: $CI_USER_TOKEN
  skip_cleanup: true
  file:
    - mindoc_linux_amd64.zip
  on:
    overwrite: true
    tags: true
    all_branches: true
    go: 1.9.2
